---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo1
  labels:
    app: echo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: rerorero/echo:latest
        env:
        - name: ID
          value: "echo"
        - name: HTTP_PORT
          value: "8080"
        - name: GRPC_PORT
          value: "9090"
        ports:
        - containerPort: 9090
          name: grpc
          protocol: TCP
        - containerPort: 8080
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: echo-grpc
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: echo
  sessionAffinity: None
  type: ClusterIP
