version: '3'

services:
  # ------------------------
  # consul server
  # ------------------------
  consul1: &consul-server
    image: consul:latest
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"
    networks:
      test:
        ipv4_address: 10.3.10.11

  consul2:
    image: consul:latest
    command: "agent -server -retry-join consul1 -client 0.0.0.0"
    networks:
      test:
        ipv4_address: 10.3.10.12

  consul3:
    image: consul:latest
    command: "agent -server -retry-join consul1 -client 0.0.0.0"
    networks:
      test:
        ipv4_address: 10.3.10.13


  # ------------------------
  # consul agent
  # ------------------------
  # agent-echo1: &consul-server
  #   image: consul:latest
  #   command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  # ------------------------
  # application
  # ------------------------
  echo1:
    image: rerorero/echo:latest
    environment:
      ID: echo1
      HTTP_PORT: 8080
      GRPC_PORT: 9090
    ports:
      - "8081:8080"
      - "9091:9090"
    networks:
      test:
        ipv4_address: 10.3.0.11

  echo1-agent:
    image: consul:latest
    command: "agent -retry-join consul1 -client 0.0.0.0"
    volumes:
      - ./config/echo1.hcl:/consul/config/echo1.hcl
    networks:
      test:
        ipv4_address: 10.3.20.11

  echo2:
    image: rerorero/echo:latest
    environment:
      ID: echo2
      HTTP_PORT: 8080
      GRPC_PORT: 9090
    ports:
      - "8082:8080"
      - "9092:9090"
    networks:
      test:
        ipv4_address: 10.3.0.12

  echo2-agent:
    image: consul:latest
    command: "agent -retry-join consul1 -client 0.0.0.0"
    volumes:
      - ./config/echo2.hcl:/consul/config/echo2.hcl
    networks:
      test:
        ipv4_address: 10.3.20.12

  echo-proxy:
    image: rerorero/echo:latest
    environment:
      ID: echo-proxy
      PROXY_HTTP_PORT: 8000
      HTTP_UPSTREAMS: "http://echo1:8080/,http://echo2:8080/"
      GRPC_UPSTREAM: "echo-grpc.com:9090"
    ports:
      - "8000:8000"
    networks:
      test:
        ipv4_address: 10.3.0.13
    extra_hosts:
      - "echo-grpc.com:10.3.0.11"
      - "echo-grpc.com:10.3.0.12"

  echo-proxy-agent:
    image: consul:latest
    command: "agent -retry-join consul1 -client 0.0.0.0"
    volumes:
      - ./config/echo-proxy.hcl:/consul/config/echo-proxy.hcl
    networks:
      test:
        ipv4_address: 10.3.20.13

networks:
  test:
    ipam:
      driver: default
      config:
        - subnet: 10.3.0.0/16
