version: '3'

services:
   echo1:
    container_name: echo1
    build:
      context: ../
      dockerfile: ./docker/echo.test.Dockerfile
    environment:
      ID: echo1
      HTTP_PORT: 8080
      GRPC_PORT: 9090
    ports:
      - "8081:8080"
      - "9091:9090"
    volumes:
      - ../:/go/src/github.com/rerorero/consul-playground
    working_dir: /go/src/github.com/rerorero/consul-playground
    command: go run ./cmd/echo/main.go
    networks:
      test:
        ipv4_address: 10.3.0.11

   echo2:
    container_name: echo2
    build:
      context: ../
      dockerfile: ./docker/echo.test.Dockerfile
    environment:
      ID: echo2
      HTTP_PORT: 8080
      GRPC_PORT: 9090
    ports:
      - "8082:8080"
      - "9092:9090"
    volumes:
      - ../:/go/src/github.com/rerorero/consul-playground
    working_dir: /go/src/github.com/rerorero/consul-playground
    command: go run ./cmd/echo/main.go
    networks:
      test:
        ipv4_address: 10.3.0.12

   echo-proxy:
    container_name: echo-proxy
    build:
      context: ../
      dockerfile: ./docker/echo.test.Dockerfile
    environment:
      ID: echo-proxy
      PROXY_HTTP_PORT: 8000
      HTTP_UPSTREAMS: "http://echo1:8080/,http://echo2:8080/"
      GRPC_UPSTREAM: "echo-grpc.com:9090"
    ports:
      - "8000:8000"
    volumes:
      - ../:/go/src/github.com/rerorero/consul-playground
    working_dir: /go/src/github.com/rerorero/consul-playground
    command: go run ./cmd/echo/main.go
    networks:
      test:
        ipv4_address: 10.3.0.13
    extra_hosts:
      - "echo-grpc.com:10.3.0.11"
      - "echo-grpc.com:10.3.0.12"

networks:
  test:
    ipam:
      driver: default
      config:
        - subnet: 10.3.0.0/16
